### ISSUE TITLE
Error in GLMs[[winner]] :  attempt to select less than one element in get1index

### ISSUE THREAD

**Issue by jrede** [reptalex/phylofactor#22]
Hey @reptalex ,

I keep getting the above error with 2 different 16S rarefied data sets (no error with raw data) and hoped you could help me understand why. 

pf <- PhyloFactor(table,tree,timestamp,choice='F',stop.fcn='KS',stop.early=TRUE)

Thanks for any help!

**Comment by reptalex** [comment]
The problem likely stems from your input variable `timestamp`. If that's a data frame with a column, say `time`, then you need to change your `frmla=Data~time` or something like that. Somehow, your glms are all returning NA such that there is no "winner".

If this pops up again, I can try to build a more informative error message, but I believe the tutorial and `? PhyloFactor` illustrate the sort of inputs allowed for the meta-data, `X`, and how to incorporate those into terms of your `frmla`.

**Comment by jrede** [comment]
Hi @reptalex,

Thanks for getting back so quickly! The timestamp variable is from a Phyloseq object (entered as physeq@sam_data$timestamp) and it runs to completion when I use the raw data (not rarefied), so I don't think its the metadata variable. The error also isn't immediate, popping up after factor 107 with my first data set. Thanks again for your help!

**Comment by reptalex** [comment]
I'm not sure - it's possible the rarefication produces a row with all zeros, or all zeros within some categorical variable (e.g. within some timestamp) - that can commonly lead to errors that are only present at later factors. Somehow, the regression is poorly posed so that all of the objectives considered at factor 107 return NA, hence 'winner' is a null vector (the error GLMs[[winner]] comes from accessing a list with a null vector).

My debugging process typically involves more carefully analyzing the regression model. If it doesn't work for every tip in your tree, then it can easily fail down the road. If it works for every tip in the tree, then it should work for internal lineages and allow a complete factorization.

For the simplest debug, do:
`table[table==0] <- 0.65`
 (this isn't what phylofactor does - it replaces 0 with 0.65*x where x is the mean of the column, but it's a quick route)
`my.glm <- function(y,x){
  xx <- data.frame('Data'=y,'X'=x)
  glm(Data~X,data=xx) %>% return()
}`

`V <- getPhyloGroups(tree) %>% sapply(ilrvec,100)`
`Y <- t(V) %*% log(table)`
`GLMs <- apply(Y,1,my.glm,x)`  #x is your timestamp, but avoid calling it that since there's an s3 object with that name
`omega <- sapply(GLMs,getStats)['F',]`

To debug, check out which `omega` values are NA and why.

**Comment by jrede** [comment]
I appreciate all your help @reptalex . Oddly, none of my omega values were NA, but for whatever reason I was able to complete the analysis by rarefying to a different sampling depth. It makes me wonder whether there's still an underlying issue with my data, but its not something I have the technical expertise to investigate. Thanks again.
