### ISSUE TITLE
CLR transformed Abundances 

### ISSUE THREAD

**Issue by biggs-biggsby** [reptalex/phylofactor#27]
Hi @reptalex!

Sorry to hit you with two questions as once. I have several identical taxa that are partitioned in different factors. Instead of showing multiple plots for the same taxon, I was hoping to aggregate the data so I can show it in a single plot, but I'm not sure my approach is appropriate. Essentially, I took same-taxon sOTUs that phylofactor identified as changing in the same direction and combined their CLR transformed values into a single plot. I understand that showing how ratios change with respect to the geometric mean is fundamentally different than how phylofactor works, so I was hoping you might have some advice on how to proceed. Thanks for any help!

**Comment by reptalex** [comment]
I'm not sure I understand your question. You're welcome to aggregate any set of species and compare them to any other single or aggregated set of species as its reference frame. Phylofactorization can reduce false positive rates by a sequentially rejective procedure. In the event of one taxon with an extremely large effect which causes the whole center of mass of microbes to have an effect, most species will appear to be changing relative to the geometric mean (the affected taxon due to their true effect, and the unaffected taxa due to their change relative to the reference frame of the center-of-mass). Phylofactorization would instead identify this one taxon, partition it from the rest, and then repeat the procedure but only comparing within groups and not across groups already identified to be changing relative to one-another. At the first iteration, phylofactor includes for consideration something like the CLR transformed tips (the ratio of a tip's abundance to the geometric mean of all other species' abundances). At the second iteration, after pulling our the affected taxon, phylofactor would find no signal.

Your resultant factors all have some effect relative to a reference frame (group1 vs. group2). You can use this information to bin/aggregate species in a post-hoc fashion if you want (we did something like that to guide longitudinal sampling of IBD patients). For example, if three sets of species, A, B, C are partitioned such that A|{B,C} increases along some axis and then B|C increases along that same axis, we don't know the extent to which A increases faster /decreases slower than {B,C}, B increases faster than C or decreases slower than C, etc. Suppose in absolute abundances A increases while B decreases slower than C - pooling A and B will give you a quantity that increases relative to C.

Check out the paper Jamie Morton, Lisa Marotz, myself and others penned, which includes the more complete description of what I mean by microbial reference frames. You're attempting to describe how one set of species changes relative to another set (in your case, relative to the geometric mean, which if you are adding these CLR transforms and check the algebra then you're probably doing a screwy ILR transform, screwy because you may not have the variance-stabilizing constant thus the size of effect may be an artifact of the number of species you pool).

https://www.nature.com/articles/s41467-019-10656-5

Otherwise, good luck! The clever choice of reference frames is the art of the science and a modern crux of sequence-count data analysis. This is also why I have my consulting company - there's a lot of tricks one could employ, ways to know if the results are significant, and more, which I keep up my sleeve (sad fact of life: open science like phylofactor doesn't pay the bills). If you're interested in more advice beyond the function of the package (does it work?), I'm happy to provide consultation at a reasonable price!

Best,
Alex

**Comment by reptalex** [comment]
P.S. Here's the paper on guiding longitudinal sampling of IBD cohorts

https://gut.bmj.com/content/67/9/1743

Outside of the paper, we found that long at the isometric log-ratio of the gammaproteobacterial lineage to the lachnospiraceae lineage (having two factors with opposing association with disease become each others' reference frame) was a reasonably good predictor using only one degree of freedom (not as good as a random forest of all gammaproteobacterial + lachnospiraceae sOTUs, but that's to be expected). This gives you some idea of the kinds of post-hoc groupings and redefinitions of microbial reference frames that you can do after obtaining your factors. You can pull out the appropriate set of species with `pf$groups[[factor]][[group_no]]` and use them to make an ilr ratio (e.g. with the function `BalanceContrast`).

**Comment by biggs-biggsby** [comment]
Thanks for being so helpful! I see what you're saying with the species A,B, and C example. I wasn't sure how to reconcile the different reference groups with combining factors initially, which is why I started using the geometric mean instead (I wasn't aware of all the post-hoc things I could do). But from what I hear from you, one or more sOTUs may have a large, but arbitrary impact on the geometric mean from sample to sample, so any change for a given sOTU could be an artifact. I'm not sure what you meant by adding the CLR transforms in addition to the ILR transform, though. My approach was to CLR transform my original sOTU table (lightly filtered), and then subset, for example, any Clostridia sOTUs that phylofactor identified across multiple factors, then plot those values. If that's the route I decide to go, I suppose I could do a standard statistical measure to compare the means of each group, although I'm not sure that would be statistically kosher since the CLR values aren't absolute values. Sorry! Not trying to get (too much) free consulting. You've been a great help and have given me a lot to think about and try!

**Comment by reptalex** [comment]
One point of clarity is that "geometric means" are ubiquitous - they're in ILR transforms (log ratios of geometric means of two groups) and CLR transforms (the geometric mean of the community).

Plotting your Clostridia sOTU clr-abundances is fine. Definitely steer clear of standard statistical measure related to the objective function you used for phylofactorization, as the Clostridia sOTUs will be a biased subset of OTUs having an unusually large effect relative to some reference frame (and that reference frame is a subset, sometimes a large subset, of "all species" being used as the reference frame for the CLR transform). The best bet for getting something like P-values from phylofactorization (barring some unpublished tricks I restrict for paying clients since NSF refused to fund it) would be to use Holm's sequentially rejective procedure on the P-values from your objective function. This is covered in the ecological monograph.

Good luck!

**Comment by biggs-biggsby** [comment]
Just as an update, the BalanceContrast function was exactly what I needed! Thanks!
